resolver: ghc-8.0.1

packages:
- '.'

extra-deps:
  - dlist-0.7.1.2
  - language-c-0.5.0
  - syb-0.6
  - QuickCheck-2.8.2
  - mtl-2.2.1
  - random-1.1
  - tf-random-0.5
  - primitive-0.6.1.0

flags: {}

extra-package-dbs: []
